### ISSUE TITLE
[windows] assuan_accept failed: Input/output error

### ISSUE THREAD

**Issue by magicbuffer** [alonbl/gnupg-pkcs11-scd#13]
Hello there,

I am unable to make gnupg-pkcs11-scd work on windows. The daemon reports the following error when I issue the command "scd learn": 

```
[...]
gnupg-pkcs11-scd[8956]: chan_0x00000000 -> OK PKCS#11 smart-card server for GnuPG ready
gnupg-pkcs11-scd[8956.0]: assuan_accept failed: Input/output error
gnupg-pkcs11-scd[8956.0]: cleanup connection
[...]
```

I have build the following softwares on an archlinux build system using mingw-w64:
- openssl-1.0.2l
- libgcrypt-1.8.1
- libassuan-2.4.3
- libgpg-error-1.27
- libksba-1.3.5
- pkcs11-helper-master
- gnupg-pkcs11-scd-0.9.1
- gnupg-2.1.23

You will find in attachment: 
- The list of mingw packages installed on my build system ([mingw-info.txt](https://github.com/alonbl/gnupg-pkcs11-scd/files/1393946/mingw-info.txt))
- The gnupg-pkcs11-scd log ([gnupg-pkcs11-scd.log](https://github.com/alonbl/gnupg-pkcs11-scd/files/1393945/gnupg-pkcs11-scd.log))
- The output of gpg-agent when issuing the "scd learn" command ([gpg-agent.txt](https://github.com/alonbl/gnupg-pkcs11-scd/files/1393941/gpg-agent.txt))
- My gnupg-pkcs11-scd configuration file ([gnupg-pkcs11-scd.conf.txt](https://github.com/alonbl/gnupg-pkcs11-scd/files/1393957/gnupg-pkcs11-scd.conf.txt))

I must say I have no idea if the constellation of gnupg packages I have built play well with gnupg-pkcs11-daemon.

Am I doing something wrong? I'll be happy to help you out, so if you need anything please do let me know.

Cheers

**Comment by alonbl** [comment]
Hi,

Thanks you for the report, long time since I checked this on Windows, and even at that time the assuan library did not work as expected. The number of hacks they did to emulate unix domain socket was amazing, and these guys tend to break the interface every other release.

I have no time nor actual use case of windows, so it will not be possible for me to fix this.

If you want to look into it, please compare the assuan_* usage between the upstream gpg-agent and ours scdaemon.c, I guess there is a problem with the emulation at the past it was a file with a process id or something.

The `gnupg-gnupg-scd --server` is the only mode that worked, not sure if gnupg on windows can use this mode.

Thanks!

**Comment by magicbuffer** [comment]
Thanks for the fast answer.

I'll try to look into it as I would love to use the daemon on windows boxes. Thanks again for all the info and pointers; I'll start there.

**Comment by alonbl** [comment]
I hope llogar patches are ok.
